import Alligator from "./models/Alligator.js";
import Bear from "./models/Bear.js";
import Cow from "./models/Cow.js";
import Dolphin from "./models/Dolphin.js";
import Elephant from "./models/Elephant.js";
import Ferret from "./models/Ferret.js";
import Giraffe from "./models/Giraffe.js";
import HammerHead from "./models/HammerHead.js";
import Iguana from "./models/Iguana.js";
import JellyFish from "./models/JellyFish.js";
import Koala from "./models/Koala.js";
import Lion from "./models/Lion.js";
import Monkey from "./models/Monkey.js";
import Newt from "./models/Newt.js";
import Octopus from "./models/Octopus.js";
import Peacock from "./models/Peacock.js";
import Quail from "./models/Quail.js";
import Rhino from "./models/Rhino.js";
import Seahorse from "./models/Seahorse.js";
import Tiger from "./models/Tiger.js";
import Umbrellabird from "./models/Umbrellabird.js";
import Vulture from "./models/Vulture.js";
import Walrus from "./models/Walrus.js";
import XRayTetra from "./models/XRayTetra.js";
import YellowEyedPenguin from "./models/YellowEyedPenguin.js";
import Zebra from "./models/Zebra.js";

let ally = new Alligator("Ally", "Green", "F", 200, 60, "big");
let bob = new Bear({ name: "Bob", color: "brown", gender: "F", weight: 50, tailLengthInch: 2, teethSize: "small" });
let carly = new Cow({ name: "Carly", color: "black", gender: "M", weight: 500, tailLengthInch: 5, teethSize: "medium" });
let darcy = new Dolphin({ name: "Darcy", color: "blue", gender: "F", weight: 2000, tailLengthInch: 10, teethSize: "big" });
let ella = new Elephant({ name: "Ella", color: "gray", gender: "F", wight: 10000, tailLengthInch: 20, teethSize: "big" });
let ferra = new Ferret({ name: "Ferra", color: "brown", gender: "F", weight: 2, tailLengthInch: 2, teethSize: "small" });
let gannon = new Giraffe({ name: "Gannon", color: "orange", gender: "M", wight: 9000, tailLengthInch: 20, teethSize: "huge" });
let hank = new HammerHead({ name: "Hank", color: "gray", gender: "M", weight: 8000, tailLengthInch: 10, teethSize: "huge" });
let iggy = new Iguana({ name: "Iggy", color: "green", gender: "F", weight: 10, tailLengthInch: 10, teethSize: "small" });
let jack = new JellyFish({ name: "Jack", color: "clear", gender: "M", weight: 5, tailLengthInch: 0, teethSize: "small" });
let keith = new Koala({ name: "Keith", color: "gray", gender: "M", weight: 20, tailLengthInch: 5, teethSize: "small" });
let lenny = new Lion({ name: "Lenny", color: "tan", gender: "M", weight: 4000, tailLengthInch: 20, teethSize: "huge" });
let monty = new Monkey({ name: "Monty", color: "black", gender: "M", weight: 40, tailLengthInch: 15, teethSize: "medium" });
let nathan = new Newt({ name: "Nathan", color: "orange", gender: "M", weight: 3, tailLengthInch: 4, teethSize: "small" });
let oscar = new Octopus({ name: "Oscar", color: "red", gender: "M", weight: 100, tailLengthInch: 0, teethSize: "medium" });
let peter = new Peacock({ name: "Peter", color: "blue", gender: "M", weight: 20, tailLengthInch: 1, teethSize: "small" });
let quinton = new Quail({ name: "Quinton", color: "gray", gender: "M", weight: 5, tailLengthInch: 2, teethSize: "small" });
let raven = new Rhino({ name: "Raven", color: "gray", gender: "F", weight: 5000, tailLengthInch: 20, teethSize: "huge" });
let sammy = new Seahorse({ name: "Sammy", color: "orange", gender: "F", weight: 10, tailLengthInch: 4, teethSize: "small" });
let tommy = new Tiger({ name: "Tommy", color: "orange", gender: "M", weight: 4000, tailLengthInch: 20, teethSize: "huge" });
let uni = new Umbrellabird({ name: "Uni", color: "black", gender: "M", weight: 5, tailLengthInch: 2, teethSize: "small" });
let vince = new Vulture({ name: "Vince", color: "black", gender: "M", weight: 10, tailLengthInch: 4, teethSize: "small" });
let wesley = new Walrus({ name: "Wesley", color: "gray", gender: "M", weight: 5000, tailLengthInch: 0, teethSize: "huge" });
let x = new XRayTetra({ name: "X", color: "clear", gender: "F", weight: 1, tailLengthInch: 1, teethSize: "small" });
let yappy = new YellowEyedPenguin({ name: "Yappy", color: "black", gender: "F", weight: 20, tailLengthInch: 2, teethSize: "small" });
let fred = new Zebra({ name: "Fred", color: "black", gender: "M", weight: 2000, tailLengthInch: 20, teethSize: "medium" });
